import type { SkillGroup } from "@/types/content";

export const skillGroups: readonly SkillGroup[] = [
  {
    id: "ai-llm-systems",
    title: "AI & LLM Systems",
    emphasis: "primary",
    skills: [
      "RAG",
      "LLMs",
      "Embeddings",
      "Semantic search",
      "Vector databases",
      "Prompt design",
      "LLM evaluation",
      "OpenAI API",
      "Local LLMs",
      "ChromaDB",
      "Sentence Transformers",
      "Ollama",
      "Chainlit",
      "Streamlit",
    ],
  },
  {
    id: "software-development",
    title: "Software Development",
    emphasis: "standard",
    skills: [
      "Python",
      "Java",
      "JavaScript",
      "C",
      "C++",
      "HTML",
      "CSS",
      "Git",
      "GitHub",
      "GitLab",
      "Testing",
      "TDD",
      "REST APIs",
    ],
  },
  {
    id: "data-backend",
    title: "Data & Backend",
    emphasis: "standard",
    skills: [
      "SQL",
      "PostgreSQL",
      "Relational database design",
      "Data normalisation",
      "JDBC",
      "Client-server systems",
      "Dashboards",
      "Data visualisation",
    ],
  },
  {
    id: "business-product-systems",
    title: "Business & Product Systems",
    emphasis: "standard",
    skills: [
      "Odoo",
      "ERP systems",
      "BPMN",
      "Mendix",
      "UML",
      "Scrum",
      "Sprint planning",
      "Requirements and workflow analysis",
    ],
  },
];
